name: Display Variable in Console

on:
  push:
    branches:
      - main

jobs:
  display-variable-job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set and display variable
        run: |
          echo "My custom variable is: $MY_VARIABLE"

        env:
          MY_VARIABLE: myvar_123

      - name: Display secret variable
        run: |
          echo "The secret variable is: ${{ secrets.MY_SECRET_VAR }}"